name: Deploy Compose Web (Wasm) to Netlify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2

      - name: Upgrade YarnLock
        run: ./gradlew kotlinUpgradeYarnLock

      - name: Build Wasm Browser Distribution
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Deploy to Netlify
        uses: netlify/actions/cli@v1
        with:
          publish-dir: ./composeApp/build/dist/wasmJs/productionExecutable
          site-id: ${{ secrets.NETLIFY_SITE_ID }}
          auth-token: ${{ secrets.NETIFY_AUTH_TOKEN }}
          production-branch: main

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_DEPLOY }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}